<?php
// ========== DEV ========== 
// define('APPLICATION', 'Catalog');
// define('HTTP_SERVER', 'http://localhost/');
// define('DIR_OPENCART', 'E:/xampp/htdocs/');
// define('DIR_APPLICATION', DIR_OPENCART . 'catalog/');
// define('DIR_EXTENSION', DIR_OPENCART . 'extension/');
// define('DIR_IMAGE', DIR_OPENCART . 'image/');
// define('DIR_SYSTEM', DIR_OPENCART . 'system/');
// define('DIR_STORAGE', 'E:/xampp/storage/');
// define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
// define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
// define('DIR_CONFIG', DIR_SYSTEM . 'config/');
// define('DIR_CACHE', DIR_STORAGE . 'cache/');
// define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
// define('DIR_LOGS', DIR_STORAGE . 'logs/');
// define('DIR_SESSION', DIR_STORAGE . 'session/');
// define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
// define('DB_DRIVER', 'mysqli');
// define('DB_HOSTNAME', 'localhost');
// define('DB_USERNAME', 'root');
// define('DB_PASSWORD', '');
// define('DB_DATABASE', 'littlemini');
// define('DB_PORT', '3306');
// define('DB_PREFIX', 'oc_');

// ========== PROD ========== 
define('APPLICATION', 'Catalog');
define('HTTP_SERVER', 'https://boutiquemignonne.fr/');
define('DIR_OPENCART', '/home/xttl3xy3mfcj/public_html/');
define('DIR_APPLICATION', DIR_OPENCART . 'catalog/');
define('DIR_EXTENSION', DIR_OPENCART . 'extension/');
define('DIR_IMAGE', DIR_OPENCART . 'image/');
define('DIR_SYSTEM', DIR_OPENCART . 'system/');
define('DIR_STORAGE', DIR_SYSTEM . 'storage/');
define('DIR_LANGUAGE', DIR_APPLICATION . 'language/');
define('DIR_TEMPLATE', DIR_APPLICATION . 'view/template/');
define('DIR_CONFIG', DIR_SYSTEM . 'config/');
define('DIR_CACHE', DIR_STORAGE . 'cache/');
define('DIR_DOWNLOAD', DIR_STORAGE . 'download/');
define('DIR_LOGS', DIR_STORAGE . 'logs/');
define('DIR_SESSION', DIR_STORAGE . 'session/');
define('DIR_UPLOAD', DIR_STORAGE . 'upload/');
define('DB_DRIVER', 'mysqli');
define('DB_HOSTNAME', 'localhost');
define('DB_USERNAME', 'littlemini');
define('DB_PASSWORD', 'GhMyhk&bCVjpMk@d');
define('DB_DATABASE', 'littlemini');
define('DB_PORT', '3306');
define('DB_PREFIX', 'oc_');